const chats = [
  {
    avatar: './img/joker.jpg',
    name: 'Jack Napier',
    prevewMessage: 'Ахахахахахахахахаххахахахахахаахаха',
    lastTime: '19:89',
  },
  {
    avatar: './img/vvp.webp',
    name: 'You know my name',
    prevewMessage: 'Крым есть? Найду моё?',
    lastTime: '20:14',
  },
  {
    avatar: './img/Propper.jpg',
    name: 'Propper',
    prevewMessage: 'Готов вычистить твоё труднодоступное место',
    lastTime: '19:58',
  },
  {
    avatar: './img/sponge.jpg',
    name: 'Sponge Bob',
    prevewMessage: 'Я не сумасшедший, я просто немного нездоров',
    lastTime: '19:99',
  },
  {
    avatar: './img/starlord.webp',
    name: 'Peter Quill',
    prevewMessage: 'Давайте кое-что уточним. Этот перец — наш трофей. Все вопросы решаются через нас. Иначе решаем их мы, причем чаще всего радикально.',
    lastTime: '19:76',
  },
    {
    avatar: './img/joker.jpg',
    name: 'Jack Napier',
    prevewMessage: 'Ахахахахахахахахаххахахахахахаахаха',
    lastTime: '19:89',
  },
  {
    avatar: './img/vvp.webp',
    name: 'You know my name',
    prevewMessage: 'Крым есть? Найду моё?',
    lastTime: '20:14',
  },
  {
    avatar: './img/Propper.jpg',
    name: 'Propper',
    prevewMessage: 'Готов вычистить твоё труднодоступное место',
    lastTime: '19:58',
  },
  {
    avatar: './img/sponge.jpg',
    name: 'Sponge Bob',
    prevewMessage: 'Я не сумасшедший, я просто немного нездоров',
    lastTime: '19:99',
  },
  {
    avatar: './img/starlord.webp',
    name: 'Peter Quill',
    prevewMessage: 'Давайте кое-что уточним. Этот перец — наш трофей. Все вопросы решаются через нас. Иначе решаем их мы, причем чаще всего радикально.',
    lastTime: '19:76',
  },
    {
    avatar: './img/joker.jpg',
    name: 'Jack Napier',
    prevewMessage: 'Ахахахахахахахахаххахахахахахаахаха',
    lastTime: '19:89',
  },
  {
    avatar: './img/vvp.webp',
    name: 'You know my name',
    prevewMessage: 'Крым есть? Найду моё?',
    lastTime: '20:14',
  },
  {
    avatar: './img/Propper.jpg',
    name: 'Propper',
    prevewMessage: 'Готов вычистить твоё труднодоступное место',
    lastTime: '19:58',
  },
  {
    avatar: './img/sponge.jpg',
    name: 'Sponge Bob',
    prevewMessage: 'Я не сумасшедший, я просто немного нездоров',
    lastTime: '19:99',
  },
  {
    avatar: './img/starlord.webp',
    name: 'Peter Quill',
    prevewMessage: 'Давайте кое-что уточним. Этот перец — наш трофей. Все вопросы решаются через нас. Иначе решаем их мы, причем чаще всего радикально.',
    lastTime: '19:76',
  },
    {
    avatar: './img/joker.jpg',
    name: 'Jack Napier',
    prevewMessage: 'Ахахахахахахахахаххахахахахахаахаха',
    lastTime: '19:89',
  },
  {
    avatar: './img/vvp.webp',
    name: 'You know my name',
    prevewMessage: 'Крым есть? Найду моё?',
    lastTime: '20:14',
  },
  {
    avatar: './img/Propper.jpg',
    name: 'Propper',
    prevewMessage: 'Готов вычистить твоё труднодоступное место',
    lastTime: '19:58',
  },
  {
    avatar: './img/sponge.jpg',
    name: 'Sponge Bob',
    prevewMessage: 'Я не сумасшедший, я просто немного нездоров',
    lastTime: '19:99',
  },
  {
    avatar: './img/starlord.webp',
    name: 'Peter Quill',
    prevewMessage: 'Давайте кое-что уточним. Этот перец — наш трофей. Все вопросы решаются через нас. Иначе решаем их мы, причем чаще всего радикально.',
    lastTime: '19:76',
  },
];